AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create lambda and apigateway

Parameters:
  TagName:
    Description: Tag
    Type: String
    Default: lambda and ApiGateway Test Stack CF

  S3LambdaCodeBucket:
    Description: BUcket in which lambda code is present
    Type: String
    Default: "vb-test-lambda-code-bucket"

  S3LambdaCodeKey:
    Description: Object name of the lambda code zip
    Type: String
    Default: 'code/package.zip'

  Component:
    Description: Name of the component
    Type: String
    Default: test-shodan-webhooks

Resources:

  LambdaDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: ShodanWebhookLambda_error_queue
      Tags:
        - Key: component
          Value: !Ref Component
        - Key: Name
          Value: webhook-error-queue
  
  LambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaDLQ
    Properties: 
      Architectures: 
        - x86_64
      Code: 
        S3Bucket: !Ref S3LambdaCodeBucket
        S3Key: !Ref S3LambdaCodeKey
      DeadLetterConfig:
        TargetArn: !GetAtt LambdaDLQ.Arn
      Description: Lambda code
      FunctionName: test-function-shodan
      Handler: lambda_function.lambda_handler
      MemorySize: 512
      PackageType: Zip
      Role: "arn:aws:iam::792514764471:role/lambdaservicerole-1"
      Runtime: python3.9
      Tags: 
        - Key: Name
          Value: webhook-lambda
        - Key: component
          Value: !Ref Component
      Timeout: 300

  WebhookRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      Description: provides api for shodan alerts automation
      Name: shodan-webhooks-restapi
      EndpointConfiguration:
        Types:
          - REGIONAL
      Policy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: execute-api:Invoke
            Resources:
              - !Sub arn:aws:execute-api:us-east-1:${AWS::AccountId}:*/*/*/webhook
      Tags: 
        - Key: Name
          Value: webhook-restapi
        - Key: component
          Value: !Ref Component

  WebhookResource:
    Type: AWS::ApiGateway::Resource
    DependsOn:
      - WebhookRestApi
    Properties:
      ParentId: !GetAtt WebhookRestApi.RootResourceId
      PathPart: webhook
      RestApiId: !Ref WebhookRestApi


  RESTApiMethod:
    Type: AWS::ApiGateway::Method
    DependsOn: 
      - LambdaFunction
    Properties: 
      AuthorizationType: NONE
      HttpMethod: POST
      ApiKeyRequired: false
      ResourceId: !Ref WebhookResource
      RestApiId: !Ref WebhookRestApi
      Integration: 
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - 
            StatusCode: "200"
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:${AWS::AccountId}:function:test-function-shodan/invocation"
      MethodResponses:
        - 
          StatusCode: "200"
      RequestModels:
        application/json: Empty

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RESTApiMethod
    Properties:
      Description: Dummy deployment Stage
      RestApiId: !Ref WebhookRestApi
      StageName: ""

  ApiStage:
    Type: AWS::ApiGateway::Stage
    DependsOn:
      - ApiDeployment
    Properties: 
      AccessLogSetting: 
          DestinationArn: 'arn:aws:logs:us-east-1:792514764471:log-group:restapilogs'
      DeploymentId: !Ref ApiDeployment
      Description: "Stage for api"
      RestApiId: !Ref WebhookRestApi
      StageName: api
      Tags: 
        - Key: Name
          Value: webhook-stage
        - Key: component
          Value: !Ref Component

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: 
      - LambdaFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:us-east-1:${AWS::AccountId}:${WebhookRestApi}/*/POST/webhook