name: Adding SSH Key
on:
  workflow_dispatch:


jobs:
  Deploy-EC2-using-GHA:
    name: 'CS sensors upload'
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo contents
        uses: actions/checkout@v3

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo ${{ github.workspace }}
          echo ${{ SSH_KEY_PATH }}
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key

      - name: upload file to github
        run: |
          ssh -T git@github.com
          
