name: Adding SSH Key
on:
  workflow_dispatch:
env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          GH_TOKEN: ${{ github.token }}

jobs:
  Deploy-EC2-using-GHA:
    name: 'CS sensors upload'
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo contents
        uses: actions/checkout@v3

      

      - name: test ssh connection
        run: |
          gh repo clone VikeshBaid/aws_gha_integration
          echo "New test file" > test1.txt
          git config --global user.name "VikeshBaid"
          git add -A
          git status 
          git commit -m "test"
          git push
